// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhGPwnAlBu3lv8Z1r_hoMWPpiA635PcDs',
    appId: '1:664044521517:web:e3639f6e3e76cf049d50a4',
    messagingSenderId: '664044521517',
    projectId: 'flutter-login-app-16887',
    authDomain: 'flutter-login-app-16887.firebaseapp.com',
    storageBucket: 'flutter-login-app-16887.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6T9QEYbVPo-mqsAviAMcbBcKqAr5mclA',
    appId: '1:664044521517:android:451c397fd8d04dc69d50a4',
    messagingSenderId: '664044521517',
    projectId: 'flutter-login-app-16887',
    storageBucket: 'flutter-login-app-16887.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwOL9JsZ2dJXHZLbX_0EQAuWNYNP0xfs4',
    appId: '1:664044521517:ios:2e0cb06155e990ad9d50a4',
    messagingSenderId: '664044521517',
    projectId: 'flutter-login-app-16887',
    storageBucket: 'flutter-login-app-16887.appspot.com',
    iosClientId: '664044521517-uea7kn9gpls3931dub2lb4qq47ch5b42.apps.googleusercontent.com',
    iosBundleId: 'com.emersonbarina.flutterDemoTheme',
  );
}
